from enum import StrEnum


class FindingType(StrEnum):
    INSTALL_HOOK_ADDED = "INSTALL_HOOK_ADDED"
    INSTALL_HOOK_REMOVED = "INSTALL_HOOK_REMOVED"
    INSTALL_HOOK_PRESENT = "INSTALL_HOOK_PRESENT"
    SIZE_INCREASE_MEDIUM = "SIZE_INCREASE_MEDIUM"
    SIZE_INCREASE_HIGH = "SIZE_INCREASE_HIGH"
    EXECUTABLE_BINARY = "EXECUTABLE_BINARY"
    OBFUSCATED_CODE = "OBFUSCATED_CODE"
    COMMAND_EXECUTION_PATTERN = "COMMAND_EXECUTION_PATTERN"


class FindingSeverity(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"
